import { StorageHelper, StorageHelperKey } from "../utils/storageHelper";
import { LevelCfgData, RankData } from "./enumConst";

class config {
    public data: RankData[] = [
        { "id": 1, "name": "Alex Walker", "level": 11, "gold": 14, "star": 3, "icon": 3 }, 
        { "id": 2, "name": "Emma Thompson", "level": 12, "gold": 15, "star": 14, "icon": 7 }, 
        { "id": 3, "name": "James Wilson", "level": 13, "gold": 16, "star": 15, "icon": 2 }, 
        { "id": 4, "name": "Sophia Davis", "level": 14, "gold": 17, "star": 16, "icon": 5 }, 
        { "id": 5, "name": "Oliver Brown", "level": 15, "gold": 18, "star": 17, "icon": 6 }, 
        { "id": 6, "name": "Isabella White", "level": 16, "gold": 19, "star": 18, "icon": 8 }, 
        { "id": 7, "name": "William Clark", "level": 17, "gold": 20, "star": 19, "icon": 7 }, 
        { "id": 8, "name": "Mia Anderson", "level": 18, "gold": 21, "star": 110, "icon": 5 }, 
        { "id": 9, "name": "Lucas Martin", "level": 19, "gold": 22, "star": 111, "icon": 8 }, 
        { "id": 10, "name": "Ava Garcia", "level": 20, "gold": 23, "star": 112, "icon": 1 }, 
        { "id": 11, "name": "Henry Rodriguez", "level": 21, "gold": 24, "star": 113, "icon": 2 }, 
        { "id": 12, "name": "Charlotte Lee", "level": 22, "gold": 25, "star": 114, "icon": 3 }, 
        { "id": 13, "name": "Benjamin King", "level": 23, "gold": 26, "star": 115, "icon": 8 }, 
        { "id": 14, "name": "Amelia Wright", "level": 24, "gold": 27, "star": 116, "icon": 5 }, 
        { "id": 15, "name": "Mason Scott", "level": 25, "gold": 28, "star": 117, "icon": 7 }, 
        { "id": 16, "name": "Harper Green", "level": 26, "gold": 29, "star": 118, "icon": 8 }, 
        { "id": 17, "name": "Ethan Adams", "level": 27, "gold": 30, "star": 119, "icon": 3 }, 
        { "id": 18, "name": "Evelyn Baker", "level": 28, "gold": 31, "star": 120, "icon": 8 }, 
        { "id": 19, "name": "Daniel Hill", "level": 29, "gold": 32, "star": 121, "icon": 8 }, 
        { "id": 20, "name": "Victoria Ross", "level": 30, "gold": 22, "star": 122, "icon": 1 }, 
        { "id": 21, "name": "Michael Ward", "level": 31, "gold": 23, "star": 123, "icon": 2 }, 
        { "id": 22, "name": "Scarlett Morris", "level": 32, "gold": 24, "star": 124, "icon": 8 }, 
        { "id": 23, "name": "Joseph Morgan", "level": 33, "gold": 25, "star": 125, "icon": 3 }, 
        { "id": 24, "name": "Chloe Cooper", "level": 34, "gold": 26, "star": 126, "icon": 8 }, 
        { "id": 25, "name": "David Reed", "level": 35, "gold": 27, "star": 127, "icon": 7 }, 
        { "id": 26, "name": "Zoe Bailey", "level": 36, "gold": 28, "star": 128, "icon": 9 }, 
        { "id": 27, "name": "Christopher Cox", "level": 37, "gold": 29, "star": 129, "icon": 8 }, 
        { "id": 28, "name": "Lily Howard", "level": 38, "gold": 30, "star": 17, "icon": 5 }, 
        { "id": 29, "name": "Andrew Butler", "level": 39, "gold": 31, "star": 17, "icon": 8 }, 
        { "id": 30, "name": "Grace Foster", "level": 11, "gold": 32, "star": 18, "icon": 8 }, 
        { "id": 31, "name": "Joshua Brooks", "level": 11, "gold": 33, "star": 19, "icon": 8 }, 
        { "id": 32, "name": "Madison Price", "level": 11, "gold": 34, "star": 10, "icon": 8 }, 
        { "id": 33, "name": "Ryan Long", "level": 11, "gold": 35, "star": 11, "icon": 5 }, 
        { "id": 34, "name": "Hannah Sanders", "level": 12, "gold": 36, "star": 12, "icon": 6 }, 
        { "id": 35, "name": "Nathan Gray", "level": 13, "gold": 37, "star": 13, "icon": 7 }, 
        { "id": 36, "name": "Aubrey Wells", "level": 14, "gold": 38, "star": 14, "icon": 8 }, 
        { "id": 37, "name": "Samuel Barnes", "level": 15, "gold": 15, "star": 15, "icon": 9 }, 
        { "id": 38, "name": "Aria Fisher", "level": 16, "gold": 16, "star": 16, "icon": 8 }, 
        { "id": 39, "name": "John Marshall", "level": 17, "gold": 17, "star": 17, "icon": 8 }, 
        { "id": 40, "name": "Zara Owen", "level": 18, "gold": 18, "star": 18, "icon": 8 }, 
        { "id": 41, "name": "Dylan Mason", "level": 19, "gold": 19, "star": 19, "icon": 8 }, 
        { "id": 42, "name": "Layla Gibson", "level": 20, "gold": 20, "star": 20, "icon": 8 }, 
        { "id": 43, "name": "Kevin Hunt", "level": 21, "gold": 21, "star": 21, "icon": 2 }, 
        { "id": 44, "name": "Nora Palmer", "level": 22, "gold": 22, "star": 22, "icon": 7 }, 
        { "id": 45, "name": "Tyler Warren", "level": 23, "gold": 23, "star": 23, "icon": 3 }, 
        { "id": 46, "name": "Lucy Dixon", "level": 24, "gold": 24, "star": 24, "icon": 7 }, 
        { "id": 47, "name": "Brandon Fox", "level": 25, "gold": 25, "star": 25, "icon": 6 }, 
        { "id": 48, "name": "Claire Murray", "level": 26, "gold": 26, "star": 26, "icon": 4 }, 
        { "id": 49, "name": "Jordan Knight", "level": 27, "gold": 27, "star": 27, "icon": 1 }, 
        { "id": 50, "name": "Violet Rose", "level": 28, "gold": 28, "star": 28, "icon": 9 }, 
        { "id": 51, "name": "Austin Stone", "level": 29, "gold": 29, "star": 29, "icon": 3 }, 
        { "id": 52, "name": "Bella Porter", "level": 30, "gold": 30, "star": 8, "icon": 7 }, 
        { "id": 53, "name": "Chase Meyer", "level": 31, "gold": 31, "star": 8, "icon": 8 }, 
        { "id": 54, "name": "Ruby Shaw", "level": 100, "gold": 31, "star": 100, "icon": 2 }, 
        { "id": 55, "name": "Leo Gordon", "level": 80, "gold": 32, "star": 80, "icon": 8 }, 
        { "id": 56, "name": "Eva Wagner", "level": 44, "gold": 33, "star": 44, "icon": 8 }, 
        { "id": 57, "name": "Max Hunter", "level": 62, "gold": 34, "star": 62, "icon": 3 }, 
        { "id": 58, "name": "Stella Black", "level": 35, "gold": 35, "star": 35, "icon": 6 }, 
        { "id": 59, "name": "Cole Parker", "level": 40, "gold": 36, "star": 40, "icon": 4 }, 
        { "id": 60, "name": "Hazel Wood", "level": 170, "gold": 37, "star": 170, "icon": 3 }, 
        { "id": 61, "name": "Owen Grant", "level": 211, "gold": 38, "star": 211, "icon": 8 }, 
        { "id": 62, "name": "Luna Hayes", "level": 210, "gold": 15, "star": 210, "icon": 8 }, 
        { "id": 63, "name": "Felix Cole", "level": 99, "gold": 16, "star": 99, "icon": 9 }, 
        { "id": 64, "name": "Nova Reid", "level": 72, "gold": 17, "star": 72, "icon": 3 }, 
        { "id": 65, "name": "Finn Walsh", "level": 37, "gold": 18, "star": 37, "icon": 1 }, 
        { "id": 66, "name": "Ivy Pierce", "level": 88, "gold": 19, "star": 88, "icon": 8 }, 
        { "id": 67, "name": "Theo Hart", "level": 82, "gold": 20, "star": 82, "icon": 6 }, 
        { "id": 68, "name": "Alice Dean", "level": 31, "gold": 21, "star": 31, "icon": 9 }, 
        { "id": 69, "name": "Miles Cross", "level": 57, "gold": 22, "star": 57, "icon": 5 }, 
        { "id": 70, "name": "Rose Flynn", "level": 78, "gold": 23, "star": 78, "icon": 2 }, 
        { "id": 71, "name": "Hugo West", "level": 165, "gold": 24, "star": 165, "icon": 1 }, 
        { "id": 72, "name": "Jade Burke", "level": 76, "gold": 25, "star": 76, "icon": 7 }, 
        { "id": 73, "name": "Atlas Ford", "level": 38, "gold": 26, "star": 38, "icon": 5 }, 
        { "id": 74, "name": "Eden Lane", "level": 65, "gold": 27, "star": 65, "icon": 6 }, 
        { "id": null, "name": "Sage Blake", "level": 176, "gold": 28, "star": 176, "icon": 8 }
    ]
}

export let RankConfig = new config();