#!/bin/bash

# =====================================================
# 快速测试命令集合
# 创建时间: 2025-08-01
# 版本: v1.0.0
# 说明: 单行命令快速测试API
# =====================================================

echo "🔍 快速测试命令集合"
echo "=========================================="
echo ""
echo "📡 1. 测试服务器连通性:"
echo "curl -s -o /dev/null -w '%{http_code}' http://119.91.142.92:3000/"
echo ""
echo "👤 2. 测试用户登录:"
echo "curl -X POST http://119.91.142.92:3000/admin/api/login -H 'Content-Type: application/json' -d '{\"pid\":\"test001\",\"password\":\"123456\"}'"
echo ""
echo "🔐 3. 测试管理员登录:"
echo "curl -X POST http://119.91.142.92:3000/admin/api/admin/login -H 'Content-Type: application/json' -d '{\"pid\":\"admin001\",\"password\":\"admin123456\"}'"
echo ""
echo "🎮 4. 测试获取用户游戏数据:"
echo "curl -X GET 'http://119.91.142.92:3000/api/user/get-game-data?userId=test001'"
echo ""
echo "💳 5. 测试获取支付模式:"
echo "curl -X GET http://119.91.142.92:3000/api/config/payment/mode"
echo ""
echo "💰 6. 测试获取用户支付记录:"
echo "curl -X GET http://119.91.142.92:3000/admin/api/payments/user/test001"
echo ""
echo "📊 7. 测试获取所有支付记录:"
echo "curl -X GET http://119.91.142.92:3000/admin/api/payments"
echo ""
echo "🗄️  8. 测试数据库连接:"
echo "mysql -ugameuser -p123456 -e 'USE game_db; SELECT COUNT(*) FROM users;'"
echo ""
echo "⚡ 9. 检查PM2服务状态:"
echo "pm2 list | grep boop-backend"
echo ""
echo "🔌 10. 检查端口监听:"
echo "netstat -tlnp | grep :3000"
echo ""
echo "📝 11. 查看服务日志:"
echo "pm2 logs boop-backend --lines 20"
echo ""
echo "=========================================="
echo "💡 使用说明:"
echo "1. 复制任意命令到终端执行"
echo "2. 观察返回结果和状态码"
echo "3. 如果返回200状态码，说明API正常"
echo "4. 如果返回错误，请检查服务器配置"
echo ""
echo "🔧 常见问题:"
echo "- 如果curl命令失败，检查网络连接"
echo "- 如果数据库命令失败，检查MySQL服务"
echo "- 如果PM2命令失败，检查PM2是否安装"
echo "- 如果端口未监听，检查后端服务是否启动" 