#!/bin/bash

# =====================================================
# 查看表结构的单行命令集合
# 创建时间: 2025-08-01
# 版本: v1.0.0
# 说明: 在MySQL中查看表结构的命令
# =====================================================

echo "🔍 查看表结构的单行命令集合"
echo "=========================================="
echo ""
echo "📋 1. 查看所有表:"
echo "SHOW TABLES;"
echo ""
echo "📊 2. 查看users表结构:"
echo "DESCRIBE users;"
echo ""
echo "📊 3. 查看user_game_data表结构:"
echo "DESCRIBE user_game_data;"
echo ""
echo "📊 4. 查看global_config表结构:"
echo "DESCRIBE global_config;"
echo ""
echo "📊 5. 查看payment_records表结构:"
echo "DESCRIBE payment_records;"
echo ""
echo "🔍 6. 查看表详细信息:"
echo "SHOW TABLE STATUS;"
echo ""
echo "🔍 7. 查看特定表详细信息:"
echo "SHOW TABLE STATUS LIKE 'users';"
echo ""
echo "🔍 8. 查看表索引:"
echo "SHOW INDEX FROM users;"
echo ""
echo "🔍 9. 查看表创建语句:"
echo "SHOW CREATE TABLE users;"
echo ""
echo "🔍 10. 查看表字段详细信息:"
echo "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'game_db' AND TABLE_NAME = 'users';"
echo ""
echo "🔗 11. 查看外键关系:"
echo "SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_SCHEMA = 'game_db' AND REFERENCED_TABLE_NAME IS NOT NULL;"
echo ""
echo "⚡ 12. 查看触发器:"
echo "SHOW TRIGGERS;"
echo ""
echo "👁️  13. 查看视图:"
echo "SHOW FULL TABLES WHERE Table_type = 'VIEW';"
echo ""
echo "📦 14. 查看存储过程:"
echo "SHOW PROCEDURE STATUS WHERE Db = 'game_db';"
echo ""
echo "📊 15. 查看表记录数量:"
echo "SELECT 'users' as table_name, COUNT(*) as record_count FROM users UNION ALL SELECT 'user_game_data', COUNT(*) FROM user_game_data UNION ALL SELECT 'global_config', COUNT(*) FROM global_config UNION ALL SELECT 'payment_records', COUNT(*) FROM payment_records;"
echo ""
echo "📊 16. 查看users表前5条记录:"
echo "SELECT * FROM users LIMIT 5;"
echo ""
echo "📊 17. 查看user_game_data表前5条记录:"
echo "SELECT * FROM user_game_data LIMIT 5;"
echo ""
echo "📊 18. 查看global_config表所有记录:"
echo "SELECT * FROM global_config;"
echo ""
echo "📊 19. 查看payment_records表前5条记录:"
echo "SELECT * FROM payment_records LIMIT 5;"
echo ""
echo "🔍 20. 查看数据库字符集和排序规则:"
echo "SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'game_db';"
echo ""
echo "=========================================="
echo "💡 使用说明:"
echo "1. 先登录MySQL: mysql -ugameuser -p123456"
echo "2. 选择数据库: USE game_db;"
echo "3. 复制任意命令执行"
echo ""
echo "🔧 快速登录并查看表结构:"
echo "mysql -ugameuser -p123456 -e \"USE game_db; SHOW TABLES; DESCRIBE users; DESCRIBE user_game_data; DESCRIBE global_config; DESCRIBE payment_records;\"" 